import streamlit as st
from openai import OpenAI
from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import re

# Your paragraph goes here - REPLACE THIS WITH YOUR OWN PARAGRAPH
YOUR_PARAGRAPH = """
Esperanza conducts pre-employment background checks on all applicants who accept an offer of employment. All offers of employment or volunteering at Esperanza are contingent upon clear results of a thorough background check. Background checks will be conducted for or requested of individuals in the following circumstances:  Job candidates to whom offers of employment have been made  Employees who are being promoted into new positions, as deemed necessary by the individual requirements of the position  Current employees whose current criminal background checks have aged will be checked every three years. Employees will be notified by HR of their expiring clearances and given instructions and a deadline for completing them.  Child abuse and Criminal: Mental Health professionals, Clinicians, nurses, social workers, medical assistants, dietitians, and any other employee whose job involves regular and repeated contact with children.  Criminal only: All other employees  For job applicants, background checks will not be requested or conducted during the employment application process, but only after a conditional offer of employment has been made in compliance with Pennsylvania law.

Pre-employment background checks will include:  Pennsylvania (PA) Criminal Background clearance  Child Abuse History check (when applicable to the position): PA Child Abuse clearance, and FBI Fingerprint-based clearance  Social Security Verification: validates the applicant's Social Security number, date of birth and former addresses.  Personal and Professional References: calls will be placed to individuals listed as references by the applicant.  Medicare/Medicaid Exclusion Checks: Checks for Medicare/Medicaid fraud history. 

An HR representative will contact employees regarding the renewal of aged clearances. Background check information will be kept on file by HR for at least five years. Final candidates for employment and volunteers will complete the background check authorization form and return it to Human Resources (HR). Human Resources will order the background checks upon receipt of the signed release form, and either internal HR staff or an employment screening service will conduct the checks. A designated HR representative will review all results.

If there are no negative results, the applicant or volunteer will continue with the onboarding process. In instances where negative or incomplete information is obtained, the hiring manager and the Director of Human Resources will conduct an assessment to determine the potential risks and liabilities related to the job's requirements and make a recommendation to the CEO regarding hiring or not hiring the individual. If a decision is made by the CEO to not hire or promote a candidate based on the result of the background check, the decision should be documented in writing and signed by the CEO. HR will follow all applicable laws regarding notifying the candidate of the rejection. If information obtained in a background check leads Esperanza to deny employment, a copy of the report will be provided to the applicant, and the applicant will have the opportunity to dispute the report’s accuracy. All background checks are conducted in conformity with the Federal Fair Credit Reporting Act, the Americans with Disabilities Act, and state and federal privacy and anti-discrimination laws. Reports are kept confidential and are only viewed by individuals involved in the hiring process. Licensed employees or contractors will be subject to other background checks as required by law and/or government contract recommendations. Sources for these reviews may include, but not limited to, System for Award Management (SAM), Office of Inspector General List of Excluded Individuals/Entities, National Practitioner Data Bank, and Pennsylvania Medicheck.

Esperanza has developed employment classifications for employees to understand their employment status. These classifications are as follows: 1. Full-time employees are those whose regularly scheduled work week consists of 32 or more hours. Employees who work 32 hours a week or more are eligible to participate in all employee benefits described more fully in this Handbook and/or the Human Resources Policy and Procedure Manual. 2. Part-time employees are those whose regularly scheduled work week consists of fewer than 32 hours per week. Part-time permanent employees are eligible to participate in employee health benefits if they are scheduled to work 24 hours a week or more. Employees scheduled to work less than 24 hours per week do not qualify to participate in group health, dental, life, and long-term disability insurance. However, all part-time employees can participate in the Esperanza Health Center 401(k) plan and, in certain cases more fully described in the Esperanza Health Center 401(k) Summary Plan Description, are eligible to receive Esperanza matching or discretionary contributions. Part-time employees that work extra hours across departments on an occasional, voluntary basis will only receive benefits entitled to them as per their hired position.

3. Per-diem employees are those employees who work less than 24 hours a week or are employed to fill in for other special needs. Such employees are not eligible to participate in employee benefits. 4. Temporary employees are employees hired to work for less than 12 months, either full or part- time. Part-time temporary employees are not eligible to participate in employee benefits. Temporary employees who work more than 30 hours per week are eligible for health insurance after 90 days (about 3 months) if upon hire, the position is designated to be 30 or more hours per week. If the number of hours per week is not known, the temporary employee will be considered a variable hour employee and subject to the rules of that employment classification. Temporary employees are entitled to sick leave according to Philadelphia law and proportionate to the hours they are scheduled to work. Sick paid time off is accrued from the date of hire to a maximum of seven days per year. 5. Probationary employees are those who have not yet completed 90 days (about 3 months) of employment with Esperanza. They accrue any vacation time, personal holiday, and sick time benefits for which they are eligible during this time but may not use these benefits until after the satisfactory completion of their probationary period. Probationary employees may be paid at a lower rate during their training period. 6. Conditional employees are those placed on conditional status as a disciplinary measure as discussed in Policy 9.2, Progressive Discipline. 7. Variable hour employees are those who, upon their start date, it cannot be determined that the employee is expected to work on average at least 8. 30 hours per week. A look- back measure of 6 months (following the 1000-hour rule) will be used to assess whether the variable hour employee will receive health insurance benefits. 

In addition, all positions are classified as exempt or non-exempt status based upon the Federal and state wage and hour laws: 1. Non-exempt hourly employees are those in support staff positions as defined by the Fair Labor Standards Act (FLSA). These employees are paid hourly and entitled to overtime pay at time and a half, if asked to work over 40 hours in the work week by Esperanza. All overtime must be approved by the employee’s supervisor prior to working. Non-exempt employees receive a one-hour lunch break; 30 minutes are unpaid and the remaining 30 minutes are designated as two 15- minute breaks. 2. Non-exempt salaried employees are those in administrative and managerial positions as defined by the FLSA. These employees are paid a salary and entitled to overtime pay at time and a half, if requested to work over 40 hours in the work week by Esperanza. Non- exempt salaried employees receive a half-hour lunch break, which is unpaid. 3. Exempt employees are those in executive, administrative, professional, and other positions as defined by the FLSA. These employees are paid a salary and are exempt from overtime. Exempt employees receive a half-hour lunch break, which is unpaid.

Esperanza will use volunteers sometimes to fulfill the health center's needs and provide educational and training opportunities to students, interns, and residents. This policy outlines the documentation and orientation requirements for volunteer positions and student rotations before starting service.  All volunteers must complete the Esperanza Health Center Volunteer or Student Rotation Application; complete an orientation of Esperanza policies; and complete and sign a HIPAA Confidentiality statement. Depending upon the service provided, volunteers may be requested to provide a copy of their Pennsylvania Criminal Background clearance.  Clinical volunteers for patient care and support positions (including students and residents) must provide:  Copies of valid, current licenses, certifications (if applicable) and CPR certificate  Evidence of OSHA training (or complete Esperanza’s OSHA training and post-test)  Evidence of current immunizations (HepB and TB)  Evidence of current liability insurance All documentation should be provided before the start of the assignment. For all volunteers and students covered by this policy, a file must be kept by the manager or supervisor and the application should be kept on file with the Human Resources Manager’s records in the Human Resources department. Volunteers, interns, and student residents may be issued an Esperanza identification (ID) card. When an ID card is required, students and/or volunteers must report to Human Resources to obtain the ID card and for the completion of onboarding.

If a former Esperanza employee returns to Esperanza after a break in service, his or her new start date will be the date of rehire. Rehired employees are probationary employees for the first 90 days of their employment, but are not eligible to use their accrued vacation, personal day, or sick paid time off until the probationary period is completed. Returning employees may or may not be rehired for the same position or same pay.

Esperanza will provide assistance to new employees in their transition into their new position at Esperanza. The Human Resources Department conducts new Employee Orientation and Onboarding. During onboarding, the employee must provide proof of identification for employment verification and complete all administrative paperwork including the following: job description review, facility tour, W-4 Employment Withholding Form, I-9 Employment Verification, and the Authorization for Direct Deposit form. OSHA Training is completed during the first 10 days of employment. Employees must complete the OSHA post-test to ensure there is a proper understanding of EHC safety policies and procedures. Orientation will normally be conducted within the employee’s first month of employment. Esperanza orientation includes an overview of Esperanza’s personnel policies and procedures, HIPAA training, information technology and electronic medical records training, health benefits orientation, and 401(k) plan orientation. Additional training and orientation will be conducted by the employee’s department for job specific training. Certain positions require participation in continuing education and training programs when such instruction is considered necessary for satisfactory job performance, licensure, or credentials. Time spent in orientation and onboarding is considered working hours and employees will be compensated for that time. Employees are encouraged to discuss questions about orientation and onboarding with their supervisor at any time. 

Esperanza expects employees to wear an Esperanza identification (ID) card to promote safety and uniformity. The identification card should be visible so all can view and allow staff to be identified as an Esperanza employee. Obstructions of your ID card should be avoided. An ID card will be issued on the first day of employment during the Human Resources Orientation. Employees are expected to wear their Esperanza ID card at all times when working. The ID card should be free from distracting stickers, pens, or anything that would conflict with the image of Esperanza’s mission. Failure to adhere to this can lead to disciplinary action. Replacement of lost identification cards will cost the employee $5.00. The ID card is the property of Esperanza and must be collected by the manager or Human Resources Director during the exit interview or when an employee is terminated. All ID cards will be returned to the Human Resources Department after termination of employment.

Esperanza typically adheres to a 40-hour work week for employees. This policy outlines the hours of operation during which the health center provides services and the regular work schedule for non- exempt and exempt employees. Esperanza’s clinical hours are Monday through Saturday. A work week begins Sunday at 12:00 a.m. and ends Saturday at 11:59 p.m. Some weekend and evening hours may be required from all employees. Hourly employees cannot begin work or perform any work related duties prior to the beginning of the normal work day (8:30 a.m. to 5:00 p.m.), unless specific authorization from the supervisor is given. Similarly, hourly employees cannot continue work beyond the end of their normal day without specific authorization from their supervisor. Exempt employees are hired to complete specific job duties and tasks that are associated with a job position without regard to specific hours. Exempt employees are expected to work the hours necessary to complete their work without the expectation of additional compensation. All employees must understand that, because of unusually heavy patient volume, special projects or emergencies, extra work time may occasionally be required. In these instances, which may occur with or without advance notice, staff members will be expected to fulfill their responsibilities as necessary to ensure good patient care. 
Esperanza desires to foster a work environment of excellence in which timeliness and consistent attendance is the professional expectation of all employees. Esperanza encourages all employees to have habits of good attendance and punctuality. Employees are expected to report to and be prepared to work by 8:30 a.m. and attend devotions, prayer groups, or other scheduled meetings between 8:30 and 9:00 a.m. unless previous authorization is given from the employee’s supervisor. Employees are not allowed to eat breakfast on work time unless approval from a supervisor is granted. Unauthorized absence(s) or tardiness will not be tolerated and may result in disciplinary action or dismissal. 

Procedure – Unscheduled Absence: At times, circumstances beyond an employee’s control may result in an unexpected absence from work for either all or part of a day. In these cases, the procedure outlined in this paragraph should be followed and supporting documentation may be requested by the employee’s supervisor or the Human Resources Director. To maintain a work environment of excellence, employees are expected to clearly and proactively communicate with their supervisor if they will be absent. If an employee is unable to report for work on a given day, he or she is required to call and speak personally with his or her supervisor no later than one hour before the scheduled starting time, unless alternative arrangements have been arranged with the employee’s supervisor. When speaking with their supervisor, employees should describe the reason for the absence. Because of the need to plan for covering open positions, messages via the supervisor’s voice mail or other third parties are not acceptable. Text communication for call-outs is allowed as determined by each department manager. Communication should occur as soon as possible but no later than 7:30 a.m. so that alternate staffing arrangements can be made. Text, as well as oral communication, should 1) be two-way; 2) close the loop about duties during the day that need to be completed in the employee’s absence; 3) be prompt; and 4) be oral, if needed, to close the loop. The employee should keep his/her phone on and be accessible to talk with the supervisor if needed. 

If employees are unable to reach their supervisor, they should contact and communicate with the next person who is designated by the supervisor. Failure to communicate directly to someone may result in a disciplinary action. If after several attempts, the employee is not able to communicate directly to a manager, he or she may leave a voicemail for the supervisor, but must follow up with a phone call at the beginning of the business day to personally inform his or her manager of the absence.

Unpaid time off is approved only under extraordinary circumstances (see 6.2 Personal and Medical Leave) and with available coverage for clinic functions. Requests for unpaid time off will be reviewed by the employee’s supervisor and the Human Resources Director for possible approval only after all accrued sick, vacation, personal, or other paid time off has been expended. Supporting documentation may be requested by the employee’s supervisor or the Human Resources Director Employees who are absent from work for three consecutive days without notice or communication with their supervisor or human resources will be considered as having quit voluntarily.

Disciplinary action will be taken in the event that an employee has four unscheduled absences, within a 60-day time period, unless prior approval for reporting late to work for activities such as attending doctor’s appointments, court hearings, school meetings, or other personal requests was given by the department supervisor 24 hours in advance. The progressive disciplinary actions for more than four unscheduled absences in a 60-day time period will include the following: 1. First verbal warning. 2. Second verbal warning. 3. Written warning. 4. First loss of vacation time accrued within the current pay period. 5. Second loss of vacation time accrued within the current pay period. 6. Review by CEO, Human Resources Director, and immediate supervisor, with employees placed in a 60-day conditional period. As stated in Section 9.2 Progressive Discipline, during the conditional period, the employee will receive full salary and benefits. If the problem is not corrected during the conditional period, employment may be terminated. If, after a successful conditional period the problem reoccurs, the employee may be terminated. 7. Temporary suspension. As stated in Section 9.2 Progressive Discipline, an employee may be temporarily suspended or permanently dismissed for the following reasons, including but not limited to, poor job performance or failure to comply with the policies and procedures of Esperanza. This is a time without pay and all accrual of benefit time will also be suspended. 8. Decision by CEO, Human Resources Director, and immediate supervisor whether to continue to employ or dismiss the employee. As stated in Section 9.2 Progressive Discipline, an employee may be dismissed at any time, including just cause as discussed in Rules of Conduct. Dismissal will be effective immediately. 

Depending on the severity of the infraction, Esperanza maintains the right to skip any of these steps and move directly to dismissal.

If employees are not able to arrive on time for work, they are required to call and speak personally with their supervisor to explain that they will be late, the reason for the tardiness, and their expected time of arrival. The employee may also text the supervisor, if this has been approved by the department manager. This call or text should be made as soon as employees know they will be late, unless alternative arrangements have been worked out with their supervisor. Messages via the supervisor’s voice mail or other third parties are not acceptable. If employees are unable to reach their supervisor, they should contact and speak with the next person who is designated by the supervisor. Failure to speak directly to someone may result in a disciplinary action. If after several attempts, the employee is not able to speak directly to a manager, he or she may leave a voicemail for the supervisor, but must follow up with a phone call to personally inform his or her manager of the tardiness

Disciplinary action will be taken in the event that an employee has four tardy incidents (more than one minute late) within a 60-day time period, unless prior approval for reporting late to work for activities such as attending doctor’s appointments, court hearings, school meetings, or other personal requests was given by the department supervisor 24 hours in advance. The progressive disciplinary actions for more than four tardy incidents in a 60-day time period will include the following: 9. First verbal warning. 10. Second verbal warning. 11. Written warning. 12. First loss of vacation time accrued within the current pay period. 13. Second loss of vacation time accrued within the current pay period. 14. Review by CEO, Human Resources Director, and immediate supervisor, with employee placed in a 60-day conditional period. As stated in Section 9.2 Progressive Discipline, during the conditional period, the employee will receive full salary and benefits. If the problem is not corrected during the conditional period, employment may be terminated. If, after a successful conditional period the problem reoccurs, the employee may be terminated. 15. Temporary suspension. As stated in Section 9.2 Progressive Discipline, an employee may be temporarily suspended or permanently dismissed for the following reasons, including but not limited to, poor job performance or failure to comply with the policies and procedures of Esperanza. This is a time without pay and all accrual of benefit time will also be suspended. 16. Decision by CEO, Human Resources Director, and immediate supervisor whether to continue to employ or dismiss the employee. As stated in Section 9.2 Progressive Discipline, an employee may be dismissed at any time, including just cause as discussed in Rules of Conduct. Dismissal will be effective immediately.

Progressive discipline related to tardiness at any level can be reversed by one step if the employee has no tardy warnings in a twelve month period from the date of the most recent warning. The reversal is made at the discretion of the Human Resources Director and the employee’s supervisor. The Director of Human Resources and the employee’s supervisor will review all tardy disciplines to confirm if a reversal is warranted. 

Esperanza expects employees to use designated time as scheduled by their department supervisor to eat lunch and take breaks.  Non-exempt hourly full time employees are entitled to a one-hour lunch break. One-half of the lunch break is paid break time and the other half is unpaid time.  Non-exempt salaried full time employees receive a half hour lunch break, which is unpaid.  Exempt employees receive a half-hour lunch break, which is unpaid. Employees are not required to log off the time clock for lunches or breaks. Employees are not allowed to eat breakfast on work time unless approval from a supervisor is granted.

Esperanza uses time clocks and, for some departments, time sheets to ensure the accuracy and completeness of employee time records and to calculate benefits. Time clocks are located at various entrances at each facility. All employees are expected to clock in upon arrival for work and clock out when leaving at the end of the scheduled work period, using their access cards or their card identification number. Onsite employees are not permitted to clock in through the ADP mobile App, laptops or computers. Only employees working remotely will be permitted to clock in using the ADP mobile App with written permission from their supervisor. This privilege can be revoked at any time. No employee will clock in or out for another employee, permit another employee to sign his or her time sheet, or in any manner falsify a time record. Failure to comply with this procedure may result in disciplinary action up to termination. In the event that an employee is absent at the end of a pay period, either the employee’s supervisor or the Human Resources Department has the right to document paid leave time (i.e., sick, vacation, etc.) on behalf of the employee. Supervisors are required to review and approve their department’s staff time sheets by 9:30 am the Monday after the pay period ends. Any errors or corrections identified after the payroll is processed must be given to the Human Resources Department in writing. The correction will be processed during the next payroll.

All employees must clock out if they have a personal medical or dental appointment, including an appointment with a clinician at Esperanza. Employee requests for time away from work for personal appointments should be given to the supervisor with as much advance notice as possible. Approval to attend the appointment will depend upon adequate coverage for the employee’s position unless the medical or dental need warrants emergency treatment. If the appointment and time away from work is approved, the time spent should be reflected in the employee’s timesheet. Following the appointment, the employee should clock back in upon return to work.

Esperanza does not allow children at work except under extenuating circumstances and with the approval of the CEO or Human Resources Director. Children of Esperanza employees must be accompanied by an adult at all times while at Esperanza. Employees can use sick time or vacation, when appropriate, if they choose to be the adult accompanying the child (for example, for a visit with a medical or dental care provider). 

Holidays Esperanza observes a number of holidays for the benefit of its employees. Each full-time employee (0.8 FTE and above) is entitled to several paid holidays. In the event that a holiday falls on an employee’s normal day off, the full-time employee will be eligible for holiday pay. Part-time employees (anything under 32 hours is Part-Time), will receive holiday pay only if the holiday is observed on their regularly scheduled work day. The following holidays are observed:  New Year’s Day.  Martin Luther King, Jr. Day, Good Friday, Memorial Day, Independence Day, Labor Day, Thanksgiving, Christmas Eve (1/2 day) - only if this falls on a Monday through Friday, Christmas Day.

Any employee who leaves employment with Esperanza is not entitled to receive pay for any unused personal days or holidays. Personal Day Eligible employees (0.6 FTE and above) also receive one paid personal day. A non-accrued personal day is defined as hours equal to a day of work for their position and is paid time off that is not taken for sickness. A personal day can be scheduled or unscheduled, but scheduled is highly preferred. Usage of the personal day is limited to one year following the employee’s anniversary date and does not carry over into the next anniversary year. If unused, it will replace a vacation day retroactively. A personal day can be taken in one hour increments.

Esperanza provides vacation time each calendar year for all eligible employees. Employees who work 24 hours or more a week are eligible to accrue vacation hours. Vacation accrual rate is based upon job classification and length of service.  Employees who work less than 40 hours per week will accrue vacation time at a rate proportionate to their employment status and hours scheduled to work.  Employees regularly scheduled to work less than 24 hours per week are permitted to make up time they were absent from their regular work week as long as the make-up hours are completed within the same pay period, with prior approval of their supervisor. Vacation time must be taken in at least 15 minute increments. Scheduling of vacations is subject to the approval of the employee’s supervisor, and to the need of employee and staff coverage in the various departments. Requests for vacation time off will be considered based upon a variety of factors such as employee seniority, adequate staffing coverage, order in which vacation requests are made to the supervisor, and employee preferences. Vacation leave is accrued from the date of hire and will be available upon completion of the probationary period. Employees may carry forward unused vacation leave time for a maximum of two years accrual. Except under special circumstances approved in advance by the CEO, there will be no advances of accrued leave (see sick leave). Employees cannot receive additional payment in lieu of vacation. Employees who work less than 24 hours a week and temporary employees do not accrue paid vacation hours; however, they can be approved for unpaid vacation proportionate to that of a full-time employee in the same position. Requests and approval of unpaid vacation follow the same request and approval procedures of paid benefit time. If the employee exceeds the allotment of unpaid time off days, he or she may receive disciplinary action. 

Non-exempt hourly employees who have worked for 1-2 years get 80 hours of vacation time per year, 100 hours when they work for 3-5 years, 120 hours when working from 6-10 years, and 160 hours after working for 11 or more years.

Managers, Directors, and Providers receive 160 hours of vacation time per year when they work for 1-5 years, 180 hours of vacation time after working 6-7 years, and 200 hours after working for 8 or more years.

Exempt Employees, such as administrators, receive 120 hours of vacation time per year when they work for 1-5 years, 140 hours when they work for 6-7 years, 160 hours when they work for 8-15 years, and 176 hours after working for 16 or more years. 

Esperanza provides sick paid time off (leave) for employees to care for themselves and their family while they are sick. Employees who work at least 40 hours per year are eligible to accrue hours of sick paid time off proportional to the hours they are scheduled to work. Employees who work less than 24 hours a week and work at least 40 hours a year will accrue sick time proportionate to that of a full-time employee in the same position. New employees are not eligible to use sick paid time off until their probationary period is completed. Temporary or seasonal employees are eligible for prorated sick paid time off, per Philadelphia’s “Promoting Health Families and Workplaces” sick leave law.

Sick paid time off is accrued from the date of hire to a maximum of seven days per year. Employees may carry forward unused sick paid time off for a maximum of 12 weeks total accrual.

Sick paid time off is to be used by eligible employees for the following approved circumstances: 1) to care for or seek treatment for their medical condition or sickness; 2) to care for or seek treatment for a family member’s medical condition or sickness; 3) to seek preventative healthcare such as routine doctor or dentist appointments, and 4) to care for themselves and family members and seek treatment, relocation, or legal services to address issues related to domestic violence, sexual assault and stalking incidents. Esperanza allows eligible employees to use sick paid time off to care for or seek treatment for the following individuals: employee, child, spouse (husband or wife by marriage; does not include “significant other”), foster child, stepchild, in-law relationships, parent, grandparent, grandchild, and siblings and child of any age incapable of self-care because of mental or physical disability.

Esperanza recognizes recuperation from childbirth as an approved circumstance for using sick paid time off for the employee birth mother and for the employee birth father caring for his wife during her recuperation period. Eligible employees may use up to one year of sick days (seven days) for continuous leave for this purpose. Eligible employees requiring additional time may request FMLA leave, if they are not already on an approved FMLA leave, or Maternity or Paternity Leave (Section 6.6), if ineligible for FMLA leave. 

The sick leave may not be used in lieu of using vacation paid time off or a personal day for purposes not included in the preceding section, Approved Circumstances for Using Sick Paid Time Off. Employees may not use sick leave for visiting individuals in the hospital, nursing facility, or other care facility.

When an employee’s sick leave lasts for three or more days, the employee may be required to provide medical documentation of the employee’s or the patient’s medical condition. When an employee’s sick leave for his/her own medical condition lasts for four or more days, the employee may be required to provide a doctor’s release to return to work. When an employee’s sick leave lasts for a minimum of five days, eligible employees must be placed on FMLA leave or Medical or Personal Leave (6.8). As noted above, employees are limited to seven days of paid sick time off for a continuous leave for the purpose of caring for self or spouse during recuperation from childbirth.

Unplanned: Calling In for Sick Leave: Call in procedures are described in Section 5.2., Attendance and Tardiness.  Planned: Requesting Sick Leave for Preventative Care: Employees are required to request leave for preventative doctor visits in advance with their supervisor and are encouraged to make preventive doctor visits during non-work hours if possible.  Planned: Requesting Continuous Sick Leave Related to Childbirth: Employees are required to request a continuous leave for their own or their wife’s recuperation from childbirth in advance with their supervisor. 

Medical documentation is generally required if an employee takes sick time the day before or after a holiday. If sufficient documentation or context for being absent is not provided, the employee may not be paid for the holiday. A medical leave certificate signed by a physician may be requested at any time following an absence for medical reasons, especially when sick leave is taken immediately before or after a holiday or vacation and/or an employee has been counseled regarding excessive absence. 

Employees who need to take sick leave in an amount greater than what they have currently accrued will be given a one-time grace occurrence and not be disciplined. Each employee is allowed one grace occurrence during the duration of employment at Esperanza. The one-time grace occurrence is time off without pay. Following the one-time grace occurrence, if an employee fails to have sufficient accrued sick time to account for absences, he or she may be subject to disciplinary actions. Employees who are on workers compensation leave and who do not have adequate benefit time to cover the waiting period may request an advance of sick time accrual from Human Resources, up to a max of seven days, to cover the first seven days of workers’ compensation leave. 

Esperanza provides full time and part time employees with paid bereavement leave to attend a funeral and mourn the recent death of relative, as follows: Parents, parent-in-law, spouse, child, step child, sibling, sibling-in-law, grandchild or grandparent will warrant 5 days for full time and 3 days for part time employees.

Aunt, uncle, cousin, niece or nephew, son-in-law, daughter-in-law will warrant 1 day of leave for full and part time employees.

An employee must request permission from his or her supervisor before taking bereavement leave, and these requests will generally be accommodated. Bereavement leave must be taken around the time of death (within 10 days) and may not be taken at a later time. Employees should be prepared to provide a funeral announcement or some formal written communication that demonstrates the reason for the bereavement leave. Employees needing to extend their bereavement leave should refer to Section 6.8 Medical and Personal Leave.

Esperanza will excuse employees from their work duties during a workday when they are called to jury duty or subpoenaed to witness duty. Witness duty includes the duty to attend court as a victim of, or a witness to, a crime or as a member of a victim’s family. The notice to report to jury duty or witness duty must be submitted to the employee’s supervisor immediately after receipt of the notice. Esperanza will compensate employees at the regular straight time rate while they are on jury duty or witness duty. To receive compensation for time away from work, employees must submit documentation provided by the court for each day of jury duty or witness duty. Any compensation paid to the employee by the court must be reimbursed to Esperanza. If the employee fails to provide documented proof of jury duty or witness duty participation, Esperanza will conclude that the absence is a paid leave and deduct the time away from work from the employee’s accrued vacation time. If the employee has no paid vacation time accrued, the time off for jury duty will be unpaid if no documentation is submitted.  

Esperanza encourages maternity or paternity leave for employees to care for the birth of a newborn child, as follows:  All employees, whether male or female, will receive one day of paid leave for the birth of their child.  Employees who work 32 hours or more per week and who are in their first year of employment at Esperanza and are therefore not eligible for leave provided under the Family Medical Leave Act (FMLA) will be eligible for maternity/paternity leave, as described in the following sections. Esperanza will allow the use of up to seven days of paid sick time off for a continuous leave for the purpose of caring for self or spouse during recuperation from childbirth. Paid sick leave will be used as described in Section 6.3, Sick Leave. Esperanza will provide up to 12 weeks of maternity or paternity leave to employees working 32 hours or more per week and who are not yet eligible for the leave provided under the FMLA, and who have completed their 90-day probationary period. Paid sick leave will be used as described in Section 6.3, Sick Leave. As noted in Section 6.3, Sick Leave, employees are limited to seven days of paid sick time off for a continuous leave for the purpose of caring for self or spouse during recuperations from childbirth. All remaining time taken during the 12 weeks will be covered by the employee’s accrued paid sick time, vacation time off or personal day, and then will be unpaid time off. The employee on maternity or paternity leave will qualify for health insurance so long as the employee continues to pay the employee portion of the health insurance premium during the unpaid time off. Insurance coverage may be terminated if the employee does not pay the employee’s portion of the health insurance premium.

In the event that both parents are employed by Esperanza, the 12 weeks of leave will be shared between the two. Esperanza will provide 12 weeks of maternity or paternity leave to employees who are in their 90 day probationary period, but they are not entitled to use their paid time off until they have completed their 90 day probationary period. The 12 weeks of maternity or paternity leave will be unpaid, but the employee will still receive the maternity/paternity one day paid leave.

In compliance with the Family and Medical Leave Act of 1993 (FMLA), as amended, regular full- and part-time employees may be permitted to take a leave of absence to care for family and medical needs. Esperanza will grant up to 12 weeks of leave (or up to 26 weeks of military caregiver leave to care for a covered service member with a serious injury or illness) during a 12-month period to eligible employees. FMLA provides employees with up to 12 weeks (or 26 weeks) of unpaid job protected leave per year to care for family and medical needs. The leave may be paid, unpaid or a combination of paid and unpaid leave, depending on the circumstances of the leave and as specified in this policy. To qualify to take family or medical leave under this policy, the employee must meet all of the following conditions: 1. The employee must have worked for Esperanza for 12 months or 52 weeks. The 12 months or 52 weeks need not have been consecutive. Separate periods of employment will be counted, provided that the break in service does not exceed seven years. Separate periods of employment will be counted if the break in service exceeds seven years due to National Guard or Reserve military service obligations or when there is a written agreement, stating Esperanza’s intention to rehire the employee after the service break. For eligibility purposes, an employee will be considered to have been employed for an entire week, even if the employee worked only part of a week. 2. The employee must have worked at least 1,250 hours during the 12-month period immediately before the date when the leave is requested to begin. To qualify as FMLA leave under this policy, the employee must be taking leave for one of the reasons listed below:  Twelve weeks of leave to cover the following conditions: 1. The birth of a child and in order to bond and care for that child. Shared between parents if both are employed by Esperanza. 2. The placement of a child for adoption or foster care and to care for the newly placed child. Shared between parents if both are employed by Esperanza. 3. To care for a spouse, child or parent (shared between spouses if both employed by Esperanza) with a serious health condition (described below). 4. The serious health condition (described below) of the employee. 5. Any qualifying exigency arising out of the fact that the employee’s spouse, son, daughter, or parent is a covered military member on “covered active duty.” 
Twenty-six weeks of leave during a 12 month period to care for the covered service member with a serious injury or illness if the eligible employee is the service member’s spouse, son, daughter, parent, or next of kin (military caregiver leave).

An employee may take leave because of a serious health condition that makes the employee unable to perform the functions of the employee's position. A serious health condition is defined as a condition that requires inpatient care at a hospital, hospice or residential medical care facility, including any period of incapacity or any subsequent treatment in connection with such inpatient care or a condition that requires continuing care by a licensed health care provider. This policy covers illnesses of a serious and long-term nature, resulting in recurring or lengthy absences. Generally, a chronic or long-term health condition that would result in a period of three consecutive days of incapacity, with the first visit to the health care provider within seven days of the onset of the incapacity and a second visit within 30 days of the incapacity, would be considered a serious health condition. For chronic conditions requiring periodic health care visits for treatment, such visits must take place at least twice a year. Employees with questions about what illnesses are covered under this FMLA policy or under Esperanza’s sick leave policy are encouraged to consult with the Human Resources Director. 

Child - includes natural, adopted, foster, stepchild, and ward  Age - under age 18 or any age incapable of self-care because of mental or physical disability  Spouse - husband or wife by marriage; does not include “significant other”  Parent - includes natural parent or any person standing or acting as the parent when the employee is the son or daughter  Serious Health Condition - illness, injury, impairment, physical or mental condition that requires in-patient care in a hospital, hospice or residential medical facility or continuing treatment by a health care provider Eligible employees who are away from work for five days (excluding scheduled vacation and up to seven days of leave related to recuperation from childbirth) must be placed on Family and Medical Leave status. The leave of absence may be with or without pay depending on whether the employee has unused paid time off accrued, including paid sick, vacation and personal day. Employees who are taking leave for their own serious health condition or for the serious health condition of an eligible family member will be required to use sick paid time off, personal day, and accrued vacation in that order before the unpaid portion of the leave begins. Sick time can only be used as outlined in the Section 6.3, Sick Leave. Employees must give 30 days’ advance notice with the FMLA Request Form for a foreseeable family or medical leave. If FMLA leave is needed unexpectedly, notice must be given as soon as is practical. Esperanza requires certification from the health care provider regarding the serious health condition within 15 days. Employees under FMLA are required to report periodically on their status and intention to return to work. Esperanza calculates a 12 week period using a rolling year. This includes the 12-month period beginning from the start of the initial FMLA leave.

Esperanza will continue health insurance under the same conditions as if the employee were working. Employees are required to continue contributing their health insurance premium amount and any contributions to a Health Savings Account (HSA), and/or Flexible Spending Account (FSA), and any voluntary benefits, if applicable, to ensure that coverage continues during FMLA leave. Upon return from leave, an employee will be restored to his or her former position or to an equivalent position with equivalent employment benefits, pay and other terms and conditions of employment. Paid time off benefits (vacation, sick and personal time) will not accrue during the unpaid portion of this leave. Upon return to work, the employee’s hire date and service time may be adjusted to reflect the period of time equal to the length of the leave. An employee who does not return from a leave of absence or who refuses a position upon return from a leave will be considered to have voluntarily terminated employment with the health center. If an employee terminates employment during or after a leave of absence, the employee will be informed of his or her COBRA rights for the continuation of health care benefits. The employee will be liable for any unpaid employee portion of the health insurance premiums through the day employment was terminated. Once an employee is termed out of EHC health insurance, they will receive a letter in the mail about their COBRA rights. Employees may call HRA Administrators at 610-774-9900 if they have any questions. The Human Resources Director is responsible for ensuring compliance with this policy and the FMLA. Any questions regarding the provisions of this policy should be directed to the Human Resources Director. 

A leave of absence without pay may be granted under certain or unusual circumstances. Medical or personal leaves of absence are not to exceed six months. Requests for such leave should be made at least three months in advance whenever possible and must be approved in advance in all cases. The employee must notify his or her supervisor of the leave request followed by a written request to the Human Resources Director. Approval of the leave request will be made at the discretion of the Director of HR or the CEO. During any authorized leave of absence, employees will have the option of continuing their health insurance coverage by paying the entire premium (employee and EHC portions of the premium). All earned, unused vacation, personal day, and sick leave can only be used if the leave is for medical purposes (if applicable). Paid time off will be paid out until paid time has been exhausted. After an extended approved leave of absence, the employee’s hire date may be adjusted to reflect the period of time equal to the length of the leave.

Failure to return at the end of an approved period of unpaid leave is likely to result in termination of employment. Employees who take an unpaid leave of absence beyond 30 days cannot be guaranteed that their position will be held for them. If the position is not held for them, they may apply for an open position meeting the individual’s qualifications and experience and Esperanza’s needs, at the new position’s rate of pay.

Esperanza provides leave for employees to permit them to fulfill their patriotic duties. Military leave is provided for employees who are enlisted or called to active duty and who are covered by the Uniformed Services Employment and Reemployment Rights Act of 1996 (USERRA), which applies to persons who serve or have served in the Armed Forces, Reserves, National Guard or other “uniformed services.” Esperanza grants employees working 32 hours or more to a maximum of 15 working days leave per year for required annual training in the National Guard or U.S. military reserves. Esperanza will pay the difference between the employee’s regular wages or salary and the military pay received by the employee. If an employee is required to serve longer than 15 days in any calendar year, no supplemental pay will be granted. Additional time off needed may be negotiated as a leave of absence without pay (see Medical or Personal Leave Policy). Employees requesting military leave must notify their supervisor as soon as possible, as well as submit a copy of their military orders to their supervisor and Human Resources department to include in their personnel file.

Esperanza desires to invest in employee rest, development and renewal after the employee has completed seven years of continuous employment by offering eligible employees a four-week sabbatical. Sabbatical time is commensurate with the employee’s full-time equivalent (FTE) status (i.e., if an employee works as a 0.4 FTE, then the employee would be given a four-week sabbatical and Esperanza would pay the employee their normal 0.4 FTE salary during that time period). Sabbaticals are given in addition to the regular employee vacation allotment. Esperanza will pay for its portion of health benefits and the employee continues to pay for his or her portion. A submission of the Sabbatical Leave form must be submitted to the employee’s supervisor at least three months prior to the start of the sabbatical and forwarded to Human Resources Director for final approval. The specific dates of the sabbatical will be determined with the approval of the employee’s department supervisor. Requests for additional vacation time added onto the sabbatical time are not typically granted. If a holiday occurs during the employee sabbatical, this is considered part of the four- week sabbatical period and the sabbatical is not extended due to the holiday.

Since Esperanza invests in sabbatical time for employee development, Esperanza expects that employees will stay at least one year after the last day of their sabbatical so that the impact of the sabbatical for the employee can be shared organizationally.

Esperanza offers health and dental group insurance benefits, life insurance coverage including Accidental Death & Dismemberment (AD&D) and Long-Term Disability benefits to all full-time permanent staff and employees who work 24 hours or more a week. Health insurance coverage for dependent children, up to age 26, is provided as an option for employees who are scheduled to work a minimum of 30 hours per week. Dental insurance is offered for the employee and dependent children, up to age 19. Spousal coverage may be available with Esperanza, depending on the spouse’s employment status and eligibility for employer benefits, as verified by the Human Resources Department of the spouse’s employer. New employees must enroll in both the health and dental insurance within 30 days of hire date or wait until the next open enrollment period (currently May-June for the July 1 effective date). Employees will be responsible to pay an annually predetermined portion of the insurance premiums, based on enrollment options for employee and dependent coverage. Esperanza will cover its portion of the health insurance costs for all full-time employees as of the date of hire and/or enrollment date for health insurance. Health and dental insurance options will be explained during the new employee orientation and enrollment forms to be completed by the employee will be provided. If the employee enrolls in health and dental coverage, payment of the employee’s portion of the premiums will be taken as a payroll deduction each pay period. Esperanza currently has a high-deductible health insurance plan. There are several options to help employees pay for expenses before reaching the deductible limit. Employees have the option of enrolling in either a Health Reimbursement Account (HRA) or a Health Savings Account (HSA) at the time of enrollment. Enrollment in a Health Savings Account (HSA) is only available during open enrollment. If an employee leaves Esperanza, then is rehired within the same year, the employee will only be eligible to enroll in an HRA, regardless of having an HSA that same plan year. That employee may choose an HSA during the open enrollment period. Employees are limited to the annual contribution limit for the plan year. Esperanza also provides employees with reimbursement of Network coinsurance amounts through a Catastrophic fund (CAT). Detailed information on plan benefits, deductibles, co-insurance and reimbursement claim forms for these accounts will be given to the employee at orientation or at open enrollment.

Employees have the option of enrolling in a Flexible Saving Account (FSA) or limited FSA, at their own expense, to cover qualified medical and dental related expenses not covered by the insurance. Enrollment in the FSA must be completed within 30 days of hire or the employee must wait until the next open enrollment period, as above. Esperanza provides, at no cost to the employee, term life insurance equal to his or her annual salary (up to $100,000), Accidental Death and Dismemberment insurance (AD&D) and Long Term Disability (LTD) benefits. Eligible employees can receive benefits up and through the last day worked. Medical and dental group insurance benefits, life insurance coverage including AD&D and LTD benefits for the employee and his or her dependents will end on the day that employment is terminated. The employee may be eligible to enroll in COBRA continuation coverage to continue health and dental insurance coverage for themselves and/or previously enrolled dependents, at their own expense. Details, enrollment options, forms and cost will be discussed with the employee upon termination of employment by the Human Resources department. 

Esperanza offers retirement plan benefits through a voluntary 401(k) Savings Plan. Esperanza has established the Esperanza Health Center 401(k) Savings Plan (the “Plan”) for the benefit of its eligible employees. The Plan provides eligible employees with a way to save for retirement on a pre-tax basis, and also provides for employer matching contributions and profit-sharing contributions for eligible participants. When employees choose to participate in the Plan, a Summary Plan Description is provided to answer the employees’ questions about the Plan. Please see the benefits plan administrator when eligible. You can register for access to the 401K by going to www.mykplan.com. The summary explains who administers the Plan, how the Plan is structured, and describes the employees’ rights and benefits under the Plan. If there is any conflict between this summary and the official Plan document, the actual text of the Plan will govern all matters. A copy of the Plan is on file at Esperanza’s principal office, 4417 North 6th Street, Philadelphia PA 19140, where the employee may inspect it during regular working hours. In addition, an employee can make a written request to his or her manager, and a copy of the Plan will be made available for the employee to read. Employees must earn a “Year of Eligibility Service” to be eligible for matching and profit-sharing contributions. Currently Esperanza will match up to 3% of an employee’s own personal contributions to the Plan. Profit-sharing contributions are decided upon in each fiscal year budget. Employees will earn a Year of Eligibility Service for the 12-month period beginning on the first day they work for Esperanza if they complete at least 700 hours of service during that period. Otherwise, employees will earn a Year of Eligibility Service when they complete at least 700 hours of service during a Plan Year (the 12-month period beginning July 1 and ending the next June 30). Employees’ Year of Eligibility Service is credited at the end of the 12-month period or Plan Year in which they complete 700 hours of service.

If employees are eligible to participate in the Plan, they will become eligible for matching and profit-sharing contributions on the first day of the month after they complete a Year of Eligibility Service. If an employee leaves and returns to EHC, they do not have to wait a year to be eligible for matching if the year was completed upon their first stint with the organization. For example, if the employee was hired on March 1, 2016, and completes at least 700 hours of service during the first 12 months of employment, the employee would be credited with a Year of Eligibility Service on February 28, 2017 (the last day of the 12-month period), and would be eligible for matching and profit-sharing contributions on April 1, 2017 (the first day of the next month). Employees’ pay received before April 1, 2017, would not be counted in determining the amount of the matching or profit-sharing contributions. 

Esperanza provides malpractice insurance under the Federal Torts Claims Act (FTCA) for all licensed clinicians including medical, dental, behavioral health, nurses, and dieticians and clinical support staff (i.e., medical and dental assistants). Under Section 224 of the Public Health Service Act, as amended by the Federally Supported Health Centers Assistance Act of 1992 and 1995, employees of eligible health centers may be deemed to be federal employees qualified for protection under the FTCA, and the coverage provides immunity from medical malpractice lawsuits resulting from the performance of medical, surgical, dental, or related functions within Esperanza’s federally-approved scope of project. Esperanza maintains this coverage through an annual renewal process that includes a review of the Center’s risk management and quality assurance procedures. The FTCA coverage is comparable to an “occurrence” policy without a monetary cap. It provides liability coverage for damage or personal injury, including death, resulting from the performance of medical, surgical, dental, or related functions by Esperanza employees, while acting within the scope of their employment with Esperanza. The FTCA coverage does not extend to a clinician’s activities outside the scope of employment with Esperanza, to a practice area for which the clinician does not have a license or has not been granted clinical privileges by the Board of Directors, or to health center volunteers. All claims are filed against the United States Government and are reviewed and/or litigated by the U.S. Department of Health and Human Services, Office of the General Counsel and the Department of Justice according to FTCA requirements. 

Esperanza may require employees to attend business related functions or activities to enhance employee performance to maintain professional licensures away from the office. Esperanza will pay the total or partial expenses of overnight travel, which include the cost of transportation (counting ground transportation fees), meals, lodging, and registration fees, as allowed by budget. Travel reimbursements considered for approval of business activities include business meetings, conferences, seminars, conventions, and selected educational functions which must be approved by the employee’s supervisor and CEO before attending. Prior to travel, the employee must submit a Request for Expense Reimbursement form to the Executive Administrator in which his or her estimated expenses are delineated. If an employee makes his or her own travel reservations, he or she is expected to travel coach or economy class. No financial commitments should be made until approval is obtained. If an employee chooses to use his or her personal vehicle, Esperanza will reimburse the employee at the standard federal travel mileage reimbursement rate in effect on the date of travel and will pay any tolls and parking. Toll and parking receipts must be provided. Esperanza will pay registration fees and lodging costs, but it is typically up to the employee to make accommodation arrangements. Esperanza will reimburse employees the sum of actual expenses incurred for up to $40 per diem for meals and miscellaneous expenses. Given the nature of our mission, simplicity and modesty in travel accommodations, meals and other expenses should be considered, and expenses kept to a minimum. For one-day travel, only parking, tolls and mileage expenses are reimbursable with a receipt and the approval of a department supervisor. Meals are generally not reimbursable for one-day travel. Volunteers may also be reimbursed for mileage at the standard federal travel mileage reimbursement rate per mile if traveling from Esperanza to a location other than their home for an assignment given by the volunteer’s supervisor. (For example, a volunteer bank courier may receive reimbursement for travel between Esperanza and the bank.)

"""

# Set up the page
st.set_page_config(page_title="Simple RAG Chatbot", page_icon="🤖")
st.title("🤖 Simple RAG Chatbot")
st.write("Ask me questions about the paragraph below!")

# Show the paragraph
with st.expander("📖 Click to see the source paragraph"):
    st.write(YOUR_PARAGRAPH)

# Initialize the embedding model (this runs once)
@st.cache_resource
def load_model():
    return SentenceTransformer('all-MiniLM-L6-v2')

# Split paragraph into sentences and create embeddings
@st.cache_data
def prepare_data(paragraph):
    # Split into sentences
    sentences = re.split(r'[.!?]+', paragraph)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    # Create embeddings
    model = load_model()
    embeddings = model.encode(sentences)
    
    return sentences, embeddings

# Get OpenAI API key from user
if 'openai_api_key' not in st.session_state:
    st.session_state.openai_api_key = ""

if 'openai_client' not in st.session_state:
    st.session_state.openai_client = None

with st.sidebar:
    st.header("⚙️ Settings")
    api_key = st.text_input(
        "Enter your OpenAI API Key:", 
        type="password", 
        value=st.session_state.openai_api_key,
        help="Get your API key from https://platform.openai.com/api-keys"
    )
    if api_key:
        st.session_state.openai_api_key = api_key
        st.session_state.openai_client = OpenAI(api_key=api_key)

# Prepare the data
sentences, embeddings = prepare_data(YOUR_PARAGRAPH)

# Chat interface
if 'messages' not in st.session_state:
    st.session_state.messages = []

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# Chat input
if prompt := st.chat_input("Ask a question about the paragraph..."):
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)
    
    # Check if API key is provided
    if not st.session_state.openai_client:
        with st.chat_message("assistant"):
            st.error("Please enter your OpenAI API key in the sidebar to use the chatbot.")
    else:
        # Find relevant sentences
        model = load_model()
        question_embedding = model.encode([prompt])
        
        # Calculate similarity
        similarities = cosine_similarity(question_embedding, embeddings)[0]
        
        # Get top 2 most similar sentences
        top_indices = np.argsort(similarities)[-2:][::-1]
        relevant_sentences = [sentences[i] for i in top_indices if similarities[i] > 0.1]
        
        if not relevant_sentences:
            relevant_sentences = [sentences[0]]  # Fallback to first sentence
        
        # Create context
        context = " ".join(relevant_sentences)
        
        # Generate response using OpenAI
        try:
            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    response = st.session_state.openai_client.chat.completions.create(
                        model="gpt-3.5-turbo",
                        messages=[
                            {"role": "system", "content": f"You are a helpful assistant. Answer the user's question based on this context: {context}. If the context doesn't contain enough information to answer the question, say so politely."},
                            {"role": "user", "content": prompt}
                        ],
                        max_tokens=150,
                        temperature=0.7
                    )
                    
                    answer = response.choices[0].message.content
                    st.write(answer)
                    
                    # Add assistant response to chat history
                    st.session_state.messages.append({"role": "assistant", "content": answer})
                    
                    # Show which sentences were used (for debugging)
                    with st.expander("🔍 Source sentences used"):
                        for sentence in relevant_sentences:
                            st.write(f"• {sentence}")
        
        except Exception as e:
            with st.chat_message("assistant"):
                st.error(f"Error: {str(e)}")
                st.write("Make sure your OpenAI API key is correct and you have credits available.")

# Instructions
with st.sidebar:
    st.header("📝 Instructions")
    st.write("""
    1. Get an OpenAI API key from https://platform.openai.com/api-keys
    2. Enter your API key in the box above
    3. Ask questions about the paragraph
    4. The chatbot will find relevant sentences and answer your questions!
    """)
    
    st.header("💡 Tips")
    st.write("""
    - Ask specific questions about the content
    - Try questions like "What is the Amazon rainforest?" or "Why is deforestation a problem?"
    - The chatbot can only answer based on the paragraph provided
    """)
